export default {
  USER_ONAUTHSTATECHANGED: 'USER_ONAUTHSTATECHANGED',
  USER_ONUSERSTATUSCHANGED: 'USER_ONUSERSTATUSCHANGED',
  DATACHANGED: 'DATACHANGED',
  USER_ONUSERIMAGECHANGED: 'USER_ONUSERIMAGECHANGED',
  INVITEDATACHANGED: 'INVITEDATACHANGED',
  RESERVATIONDATA: 'RESERVATIONDATA',
  RESERVATIONDATACHANGED: 'RESERVATIONDATACHANGED',
  RESERVATIONDATALENGTH: 'RESERVATIONDATALENGTH',
  INVITEDATALENGTH: 'INVITEDATALENGTH',
}